name: Build Python EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile \
          --windowed \
          --clean \
          --noupx \
          --hidden-import "pygame" \
          --name "Main" main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Main-windows-exe
          path: dist/*
          if-no-files-found: error
